version: 2

sources:
  - name: company
    database: dataengineers-407810
    schema: raw_airbyte_dataset  
    tables:
      - name: table
        identifier: "v3"
        #loaded_at_field: _batched_at
        #freshness:
          #warn_after: {count: 12, period: hour}
          #error_after: {count: 24, period: hour}



          #dbt source freshness



