version: 2

sources:
  - name: stackoverflow
    database: bigquery-public-data  
    schema: stackoverflow  
    tables:
      - name: answers
        identifier: "posts_answers"

      - name: questions
        identifier: "posts_questions"

